// packages/vite-react/src/App.jsx
import { Outlet, Link } from "react-router-dom";
import "./App.css";

function App() {
  return (
    <div className="container">
      <h1>Vite + React + Legacy</h1>
      <div style={{ marginBottom: "20px" }}>
        <Link to={"/vite-react/home"}>Go to Home</Link>
        <Link style={{ marginLeft: "20px" }} to={"/vite-react/about"}>
          Go to About
        </Link>
      </div>
      <Outlet></Outlet>
    </div>
  );
}

export default App;

// packages/vite-vue3/src/App.vue
<template>
  <div class="container">
    <h1>Vite + Vue3 + Legacy</h1>
    <div style="margin-bottom: 20px">
      <router-link :to="{name: 'Home'}">Go to Home</router-link>
      <router-link style="margin-left: 20px" :to="{name: 'About'}">Go to About</router-link>
    </div>
    <router-view></router-view>
  </div>
</template>

<style>
.container {
  text-align: center;
  color: #42b883;
  border: 1px solid #42b883;
}
</style>
