// packages/vite-vue2/src/App.vue
<template>
  <div class="container">
    <h1>Vite + Vue2</h1>
    <div style="margin-bottom: 20px">
      <router-link :to="{ name: 'Home' }">Go to Home</router-link>
      <router-link style="margin-left: 20px" :to="{ name: 'About' }">Go to About</router-link>
    </div>
    <router-view></router-view>
  </div>
</template>

<style>
.container {
  text-align: center;
  color: #34495e;
  border: 1px solid #34495e;
}
</style>

// packages/vite-react/src/App.jsx
import { Outlet, Link } from "react-router-dom";
import "./App.css";

function App() {
  return (
    <div className="container">
      <h1>Vite + React</h1>
      <div style={{ marginBottom: "20px" }}>
        <Link to={"/vite-react/home"}>Go to Home</Link>
        <Link style={{ marginLeft: "20px" }} to={"/vite-react/about"}>
          Go to About
        </Link>
      </div>
      <Outlet></Outlet>
    </div>
  );
}

export default App;
